### ISSUE TITLE
Responsiveness Design Bug

### ISSUE THREAD

**Issue by subhamX** [creativecommons/creativecommons.github.io-source#490]
## Description
The [Write a Blog Post](https://opensource.creativecommons.org/community/write-a-blog-post/) page under the community tab isn't responsive and a lot of content is getting clipped.

## Screenshots
I have adjusted the viewport to `1295px`. Please notice that the `Archives` tab on the navbar isn't visible.

![image](https://user-images.githubusercontent.com/43654114/91398859-89833700-e85a-11ea-8b62-4b6b7410388d.png)

Similarly, the content of the post isn't visible for some widths. You can refer to this [link](https://youtu.be/jSqC_tOMshY) for a live demo.

Additionally, for screens with viewport `<769px` I think everything is just perfect.

## Reproduction
Please remove the `overflow-x: hidden;` property on the `body` element just to visualize the clipped content. You will be able to notice a very long horizontal scrollbar. 

## Environment
 - Device: Laptop
 - OS: Windows10
 - Browser: Chrome and Firefox

## Resolution

- [ ] I would be interested in resolving this bug.

**Comment by Heisenberg399** [comment]
I can try..assign it to me

**Comment by Aakash2408** [comment]
is this done or i can take this?

**Comment by kgodey** [comment]
@Aakash2408 go ahead

**Comment by Aakash2408** [comment]
I guess this issue is already resolved.

**Comment by Aakash2408** [comment]
![Screenshot from 2020-09-14 15-46-01](https://user-images.githubusercontent.com/47134609/93074079-7ddca080-f6a1-11ea-8edd-2e3ca7e767e8.png)

**Comment by kgodey** [comment]
The issue is not resolved, a lot of content is getting cut off.

**Comment by zackkrida** [comment]
@Aakash2408 + @kgodey the issue is caused by our code blocks exceeding 100% of the page width. Some css is needed to adjust those.

**Comment by nimishbongale** [comment]
@Aakash2408 @kgodey @zackkrida 

I think an `overflow-wrap: break-word` might fix it, although I'm not a 100% certain. Maybe fidgeting around with `overflow-x` may also work.

**Comment by Yashs911** [comment]
Hi, @dhruvkb @nimishbongale I would like to work on this if this issue is still open. If you could please guide me on what all changes do I need to make and in which file?

**Comment by Yashs911** [comment]
Hi, @dhruvkb adding width: 85%; in .content fixes this issue but I don't know whether it will be an ideal fix. 
Should I go ahead with this?
![fix](https://user-images.githubusercontent.com/64412143/95012236-a62e3e00-0654-11eb-8de2-0cc326fd0637.JPG)

**Comment by dhruvkb** [comment]
@Yashs911 any solution that needs a hardcoded arbitrary value is not ideal. I would recommend finding an alternative, cleaner solution to this.

**Comment by Yashs911** [comment]
@dhruvkb I am unable to find the files location is it in this repo or some other repo?

**Comment by dhruvkb** [comment]
Which file are you looking for? All files are in this repo itself.

**Comment by Yashs911** [comment]
Hi, @dhruvkb according to the readme file this site is hosted on lektor and there is no installation command for windows. and I am currently using windows.

**Comment by dhruvkb** [comment]
To run this on Windows, you have to set up a Python and Node.js environment. Both of those have instructions for Windows on their websites.

**Comment by nimishbongale** [comment]
>according to the readme file this site is hosted on lektor and there is no installation command for windows and I am currently using windows.

They do have a very gimmicky way of getting it installed.
On windows, please run the following command on powershell in admin mode:

```powershell
(new-object net.webclient).DownloadString('https://www.getlektor.com/installer.py') | python
```

This should install lektor.
Please also make sure you have nodejs, python and pipenv installed to run the same like @dhruvkb mentioned.

You can use [chocolatey](https://chocolatey) to install these if you wish.

```cmd
choco install python
choco install nodejs
pip install pipenv
```

I'm currently working on having lektor installed via chocolatey (and infact it can be, but it still needs to pass some verification testing)

Please refer to this issue: 
- https://github.com/lektor/lektor/issues/814#issuecomment-703309593

**Comment by Yashs911** [comment]
@nimishbongale I already have python 3.8 and node.js installed. How do I install pipenv? and which editor should I use for open source contribution? Currently, I am using sublime text and I also have anaconda and pycharm installed. I am not that familiar with setting a virtual environment.

**Comment by nimishbongale** [comment]
@Yashs911 

Alright. If you have nodejs and python 3.8 installed, all you would need is pip, and you could do `pip install pipenv` and it would work just fine.

As far as the editor is concerned, I prefer VSCode. But honestly, this should really not be a concern when it comes to Open Source Contribution. The commands that I talked of earlier have to be executed in the terminal and not via an IDE such as Pycharm. (although the project could be run inside an IDE)

There really not much about setting up a virtual environment. `pipenv` handles that pretty conveniently and can be installed from [https://pypi.org/](https://pypi.org/). Just make sure you have python, nodejs, lektor and pipenv in your path.

**Comment by DDuplinszki** [comment]
Hi guys,

Due to the inactivity, I've started to look into it. However, I'm unable to modify the css file because it's generated, if I modify it, it has no effect on restart. Maybe I don't have the necessary knowledge to handle these kind of environments, however if you would like to and if it's ok with the assignee, I can just put the solution over here in the comments.

**Comment by Yashs911** [comment]
@DDuplinszki if you want you can create a PR for this issue.

**Comment by khushishikhu** [comment]
@Yashs911 may i work on this issue

**Comment by Yashs911** [comment]
@khushishikhu Currently no one is assigned so I guess you can work. But it would be better if you ask @dhruvkb.

**Comment by nimishbongale** [comment]
@khushishikhu you may.

**Comment by khushishikhu** [comment]
sure! @nimishbongale  @Yashs911

**Comment by khushishikhu** [comment]
@nimishbongale can you please give me the reference file that i can do the css editing. As i have setup locally but unable to find the file for css editing.

**Comment by dhruvkb** [comment]
@khushishikhu all the CSS files are in the [`webpack/sass` folder](https://github.com/creativecommons/creativecommons.github.io-source/tree/master/webpack/sass). Most likely, the file you're looking for would be `home-page.scss`.

**Comment by Yashs911** [comment]
@dhruvkb I just found the solution and the file and if it's okay with @khushishikhu. Can I create a PR.

**Comment by Yashs911** [comment]
![cc](https://user-images.githubusercontent.com/64412143/97109267-49282400-16f8-11eb-8033-f01040c9bd48.JPG)
width:75%; will solve the problem

**Comment by DDuplinszki** [comment]
hi guys, I know it's closed and stuff. However, probably the best responsive solution would be to add min-width: 0;  min-height: 0; 
It's due to the default settings of flexbox where these options on "auto". Even if no one will use this in this particular case, I felt like it would be useful to share that whenever you have this problem, you can try this solution as well.
